// Generated by https://quicktype.io

export interface TopLevel {
  page:          number;
  results:       Result[];
  total_pages:   number;
  total_results: number;
}

export interface Result {
  adult:             boolean;
  backdrop_path:     string;
  id:                number;
  name:              string;
  original_language: OriginalLanguage;
  original_name:     string;
  overview:          string;
  poster_path:       string;
}

export enum OriginalLanguage {
  De = "de",
  En = "en",
}
