// Generated by https://quicktype.io

export interface Paginas {
  results:       Result[];
  page:          number;
  total_pages:   number;
  total_results: number;
}

export interface Result {
  id:    number;
  adult: boolean;
}
